module.exports = {
    fontFamily: {
        sans: [
            'ui-sans-serif',
            'system-ui',
            '-apple-system',
            'BlinkMacSystemFont',
            '"Segoe UI"',
            'Roboto',
            '"Helvetica Neue"',
            'Arial',
            '"Noto Sans"',
            'sans-serif',
            '"Apple Color Emoji"',
            '"Segoe UI Emoji"',
            '"Segoe UI Symbol"',
            '"Noto Color Emoji"',
        ],
        /*         serif: [
            'ui-serif',
            'Georgia',
            'Cambria',
            '"Times New Roman"',
            'Times',
            'serif',
        ], */
        mono: [
            '"SFMono-Regular"',
            'Consolas',
            '"Liberation Mono"',
            'Menlo',
            'Courier',
            'monospace',
        ],
        heading: ['Quark'],
        title: [],
        display: [
            'Inter',
            '-apple-system',
            'BlinkMacSystemFont',
            '"Helvetica Neue"',
            '"Segoe UI"',
            'Oxygen',
            'Ubuntu',
            'Cantarell',
            '"Open Sans"',
            'sans-serif',
        ],
        content: [
            'Manrope',
            '-apple-system',
            'BlinkMacSystemFont',
            '"Segoe UI"',
            'Helvetica',
            'Arial',
            'sans-serif',
            '"Apple Color Emoji"',
            '"Segoe UI Emoji"',
            '"Segoe UI Symbol"',
        ],
    },
}
